services:
  #nextjs service
  nextapp:
    container_name: nextapp
    image: nextapp:2.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - 3000:3000
    environment:
    - NEXT_PUBLIC_API_URL=http://flaskapp:4000
    depends_on:
      - flaskapp
      
# flask service
  # flask service
  flaskapp:
    container_name: flaskapp
    image: flaskapp:2.0.0
    build:
      context: ./main
      dockerfile: flask.dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
    command: >
      python app.py


# db service
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 2

volumes:
  pgdata: {}